### ISSUE TITLE
App Crashes on Splash screen

### ISSUE THREAD

**Issue by vaibhavgadekar** [blendtale/react-native-form-progress#11] opened 2021-04-09 07:41 UTC
java.lang.IllegalStateException: com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 175
 detail: View tag:147
  children(11): [
55,63,67,73,79,85,93,97,109,123,139,
 ],
  viewsToAdd(1): [
[0,175],
 ],

	at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:390)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1027)
	at android.view.Choreographer.doCallbacks(Choreographer.java:841)
	at android.view.Choreographer.doFrame(Choreographer.java:769)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 175
 detail: View tag:147
  children(11): [
55,63,67,73,79,85,93,97,109,123,139,
 ],
  viewsToAdd(1): [
[0,175],
 ],

	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:487)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:209)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1088)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	... 13 more

**Comment by irohitb** [comment] 2021-04-09 07:51
@vaibhavgadekar looking into it. 

Can you please let me know what you did? Some code to reproduce it?

**Comment by irohitb** [comment] 2021-04-15 11:07
Closing this issue since the author of issue didn't share any update.  (Reached out to him over email as well)

**Closed as completed by irohitb** 2021-04-15 11:07 UTC
Labels: bug
